use crate::docset::{DocSet, SeekDangerResult};
use crate::query::scorer::PruningScorer;
use crate::query::Scorer;
use crate::{DocId, Score, TERMINATED};

/// A `PruningScorer` that combines an inner scoring query (`TScorer: PruningScorer`) with
/// a filter (`TFilter: Scorer`).
///
/// Supports two execution modes depending on filter density:
/// - Filter-driven mode (when `filter.cost() < scorer.cost() / 16`): the sparse filter drives
///   iteration via `filter.advance()`, and `scorer.seek(f_doc)` leaps to filter candidates.
/// - Scorer-driven mode (default / denser filters): `scorer` drives candidate generation, and
///   `filter.seek_danger(s_doc)` performs O(1) point-checks. On misses, `scorer` leaps forward via
///   `scorer.seek(bound)` only when `bound > s_doc + 1` (skipping non-matching ranges), or advances
///   via `scorer.advance()` when `bound == s_doc + 1`.
pub struct FilteredPruningScorer<TScorer: PruningScorer, TFilter: Scorer> {
    scorer: TScorer,
    filter: TFilter,
    filter_boost: Score,
    filter_driven: bool,
    current_doc: DocId,
}

impl<TScorer: PruningScorer, TFilter: Scorer> FilteredPruningScorer<TScorer, TFilter> {
    /// Creates a new `FilteredPruningScorer` from an inner pruning scorer and a filter scorer.
    ///
    /// # Panics
    /// Panics if `filter.constant_score()` returns `None`. Dynamic block pruning requires
    /// an invariant constant score contribution from the filter to prune blocks without
    /// false negatives.
    #[allow(dead_code)]
    pub fn new(scorer: TScorer, filter: TFilter) -> Self {
        let boost = filter
            .constant_score()
            .expect("filter must produce a constant score for dynamic block pruning");
        Self::new_with_filter_boost(scorer, filter, boost)
    }

    /// Creates a new `FilteredPruningScorer` with an explicit filter boost score.
    ///
    /// The filter must produce this constant score for every document. Dynamic block pruning
    /// subtracts `filter_boost` from the threshold to determine which blocks can be skipped;
    /// variable filter scores would violate this guarantee and cause false negatives.
    pub fn new_with_filter_boost(scorer: TScorer, filter: TFilter, filter_boost: Score) -> Self {
        // Select filter-driven mode when the filter is significantly sparser than the scorer.
        let filter_driven = filter.cost() < scorer.cost() / 16;

        let mut filtered = FilteredPruningScorer {
            scorer,
            filter,
            filter_boost,
            filter_driven,
            current_doc: 0,
        };

        // Short-circuit if either stream is empty.
        if filtered.scorer.doc() == TERMINATED || filtered.filter.doc() == TERMINATED {
            filtered.current_doc = TERMINATED;
            return filtered;
        }

        // Align to the first document matching both scorer and filter.
        if filter_driven {
            let f_doc = filtered.filter.doc();
            filtered.align_filter_driven(f_doc);
        } else {
            let f_doc = filtered.filter.doc();
            let mut s_doc = filtered.scorer.doc();
            if s_doc < f_doc {
                s_doc = filtered.scorer.seek(f_doc);
            }
            filtered.align_scorer_driven(s_doc);
        }

        filtered
    }

    #[inline]
    #[cfg(test)]
    pub(crate) fn is_filter_driven(&self) -> bool {
        self.filter_driven
    }

    /// Sparse filter iteration: leapfrogs between filter and scorer, allowing the
    /// inner BMW scorer to skip non-competitive blocks to reach filter matches.
    fn align_filter_driven(&mut self, mut f_doc: DocId) -> DocId {
        let mut s_doc = self.scorer.doc();
        while f_doc != TERMINATED && s_doc != TERMINATED {
            if f_doc < s_doc {
                f_doc = self.filter.seek(s_doc);
            } else if s_doc < f_doc {
                s_doc = self.scorer.seek(f_doc);
            } else {
                debug_assert!(
                    (self.filter.score() - self.filter_boost).abs()
                        <= 1e-5 * (self.filter_boost.abs() + 1.0),
                    "Filter declared constant score {}, but produced {} on doc {}",
                    self.filter_boost,
                    self.filter.score(),
                    s_doc,
                );
                self.current_doc = s_doc;
                return s_doc;
            }
        }
        self.current_doc = TERMINATED;
        TERMINATED
    }

    /// Dense filter iteration: candidate documents are generated by `scorer` and
    /// point-checked against `filter` via `seek_danger`.
    fn align_scorer_driven(&mut self, mut s_doc: DocId) -> DocId {
        while s_doc != TERMINATED {
            match self.filter.seek_danger(s_doc) {
                SeekDangerResult::Found => {
                    debug_assert!(
                        (self.filter.score() - self.filter_boost).abs()
                            <= 1e-5 * (self.filter_boost.abs() + 1.0),
                        "Filter declared constant score {}, but produced {} on doc {}",
                        self.filter_boost,
                        self.filter.score(),
                        s_doc,
                    );
                    self.current_doc = s_doc;
                    return s_doc;
                }
                SeekDangerResult::SeekLowerBound(bound) => {
                    if bound == TERMINATED {
                        // Filter has no documents >= s_doc.
                        break;
                    } else if bound > s_doc + 1 {
                        // Range/block miss: leap scorer directly to the next possible filter match.
                        s_doc = self.scorer.seek(bound);
                    } else {
                        // Point miss: advance scorer within the current block without triggering a
                        // seek.
                        s_doc = self.scorer.advance();
                    }
                }
            }
        }
        self.current_doc = TERMINATED;
        TERMINATED
    }
}

impl<TScorer: PruningScorer, TFilter: Scorer> Scorer for FilteredPruningScorer<TScorer, TFilter> {
    #[inline]
    fn score(&mut self) -> Score {
        self.scorer.score() + self.filter_boost
    }

    #[inline]
    fn constant_score(&self) -> Option<Score> {
        Some(self.scorer.constant_score()? + self.filter_boost)
    }
}

impl<TScorer: PruningScorer, TFilter: Scorer> PruningScorer
    for FilteredPruningScorer<TScorer, TFilter>
{
    #[inline]
    fn set_threshold(&mut self, score: Score) {
        let scorer_threshold = if score == Score::MIN {
            Score::MIN
        } else {
            score - self.filter_boost
        };
        self.scorer.set_threshold(scorer_threshold);
    }
}

impl<TScorer: PruningScorer, TFilter: Scorer> DocSet for FilteredPruningScorer<TScorer, TFilter> {
    fn advance(&mut self) -> DocId {
        if self.current_doc == TERMINATED {
            return TERMINATED;
        }
        if self.filter_driven {
            let f_doc = self.filter.advance();
            self.align_filter_driven(f_doc)
        } else {
            let s_doc = self.scorer.advance();
            self.align_scorer_driven(s_doc)
        }
    }

    fn seek(&mut self, target: DocId) -> DocId {
        if target <= self.current_doc {
            return self.current_doc;
        }
        if self.filter_driven {
            let f_doc = self.filter.seek(target);
            self.align_filter_driven(f_doc)
        } else {
            let s_doc = self.scorer.seek(target);
            self.align_scorer_driven(s_doc)
        }
    }

    #[inline]
    fn doc(&self) -> DocId {
        self.current_doc
    }

    fn size_hint(&self) -> u32 {
        self.scorer.size_hint().min(self.filter.size_hint())
    }

    fn cost(&self) -> u64 {
        self.scorer.cost().min(self.filter.cost())
    }
}

#[cfg(test)]
mod tests {
    use std::sync::{Arc, Mutex};

    use super::*;
    use crate::docset::SeekDangerResult;

    #[derive(Default)]
    struct Trace {
        scorer_advances: usize,
        scorer_seeks: Vec<DocId>,
        filter_advances: usize,
        filter_seeks: Vec<DocId>,
        filter_seek_dangers: Vec<DocId>,
    }

    struct MockScorer {
        docs: Vec<DocId>,
        pos: usize,
        cost_val: u64,
        trace: Arc<Mutex<Trace>>,
    }

    impl MockScorer {
        fn new(docs: Vec<DocId>, cost_val: u64, trace: Arc<Mutex<Trace>>) -> Self {
            Self {
                docs,
                pos: 0,
                cost_val,
                trace,
            }
        }
    }

    impl DocSet for MockScorer {
        fn advance(&mut self) -> DocId {
            self.trace.lock().unwrap().scorer_advances += 1;
            if self.pos < self.docs.len() {
                self.pos += 1;
            }
            self.doc()
        }

        fn seek(&mut self, target: DocId) -> DocId {
            self.trace.lock().unwrap().scorer_seeks.push(target);
            while self.pos < self.docs.len() && self.docs[self.pos] < target {
                self.pos += 1;
            }
            self.doc()
        }

        fn doc(&self) -> DocId {
            if self.pos < self.docs.len() {
                self.docs[self.pos]
            } else {
                TERMINATED
            }
        }

        fn size_hint(&self) -> u32 {
            self.docs.len() as u32
        }

        fn cost(&self) -> u64 {
            self.cost_val
        }
    }

    impl Scorer for MockScorer {
        fn score(&mut self) -> Score {
            1.0
        }

        fn constant_score(&self) -> Option<Score> {
            Some(1.0)
        }
    }

    impl PruningScorer for MockScorer {
        fn set_threshold(&mut self, _score: Score) {}
    }

    struct MockFilter {
        docs: Vec<DocId>,
        pos: usize,
        cost_val: u64,
        trace: Arc<Mutex<Trace>>,
    }

    impl MockFilter {
        fn new(docs: Vec<DocId>, cost_val: u64, trace: Arc<Mutex<Trace>>) -> Self {
            Self {
                docs,
                pos: 0,
                cost_val,
                trace,
            }
        }
    }

    impl DocSet for MockFilter {
        fn advance(&mut self) -> DocId {
            self.trace.lock().unwrap().filter_advances += 1;
            if self.pos < self.docs.len() {
                self.pos += 1;
            }
            self.doc()
        }

        fn seek(&mut self, target: DocId) -> DocId {
            self.trace.lock().unwrap().filter_seeks.push(target);
            while self.pos < self.docs.len() && self.docs[self.pos] < target {
                self.pos += 1;
            }
            self.doc()
        }

        fn seek_danger(&mut self, target: DocId) -> SeekDangerResult {
            self.trace.lock().unwrap().filter_seek_dangers.push(target);
            // Simulate point check or bounded skip
            if self.docs.contains(&target) {
                while self.pos < self.docs.len() && self.docs[self.pos] < target {
                    self.pos += 1;
                }
                SeekDangerResult::Found
            } else {
                // Find next matching doc
                let next = self.docs.iter().copied().find(|&d| d > target);
                match next {
                    Some(d) => SeekDangerResult::SeekLowerBound(d),
                    None => SeekDangerResult::SeekLowerBound(TERMINATED),
                }
            }
        }

        fn doc(&self) -> DocId {
            if self.pos < self.docs.len() {
                self.docs[self.pos]
            } else {
                TERMINATED
            }
        }

        fn size_hint(&self) -> u32 {
            self.docs.len() as u32
        }

        fn cost(&self) -> u64 {
            self.cost_val
        }
    }

    impl Scorer for MockFilter {
        fn score(&mut self) -> Score {
            0.0
        }

        fn constant_score(&self) -> Option<Score> {
            Some(0.0)
        }
    }

    #[test]
    fn test_driver_selection() {
        let trace = Arc::new(Mutex::new(Trace::default()));
        // Sparse filter: cost 5 < 100 / 16 (6) -> filter-driven
        let scorer = MockScorer::new(vec![1, 2, 3, 4, 5], 100, trace.clone());
        let filter = MockFilter::new(vec![2, 4], 5, trace.clone());
        let fps = FilteredPruningScorer::new(scorer, filter);
        assert!(fps.is_filter_driven());

        // Dense filter: cost 10 >= 100 / 16 (6) -> scorer-driven
        let scorer = MockScorer::new(vec![1, 2, 3, 4, 5], 100, trace.clone());
        let filter = MockFilter::new(vec![2, 4], 10, trace.clone());
        let fps = FilteredPruningScorer::new(scorer, filter);
        assert!(!fps.is_filter_driven());
    }

    #[test]
    fn test_scorer_driven_point_miss_advances_without_seek() {
        let trace = Arc::new(Mutex::new(Trace::default()));
        // Scorer has docs 0, 1, 2, 3, 4. Filter has docs 0, 2, 4 (missing 1 and 3).
        // On doc 0: matches!
        // On advancing from doc 0: scorer advances to 1.
        // Doc 1 is a point miss in filter: next doc in filter is 2. bound = 1 + 1 = 2.
        // Since bound == s_doc + 1, scorer.advance() is called to reach 2, NOT scorer.seek(2).
        let scorer = MockScorer::new(vec![0, 1, 2, 3, 4], 100, trace.clone());
        let filter = MockFilter::new(vec![0, 2, 4], 50, trace.clone());
        let mut fps = FilteredPruningScorer::new(scorer, filter);
        assert!(!fps.is_filter_driven());

        // Initial alignment: doc 0 matches immediately
        assert_eq!(fps.doc(), 0);
        assert_eq!(trace.lock().unwrap().scorer_advances, 0);
        assert!(trace.lock().unwrap().scorer_seeks.is_empty());

        // Advance: scorer advances to 1 (advances=1), filter seek_danger(1) returns
        // SeekLowerBound(2). Since bound == 2 == s_doc + 1, scorer advances to 2
        // (advances=2), seek_danger(2) -> Found. Scorer was never seek()'d!
        assert_eq!(fps.advance(), 2);
        assert_eq!(trace.lock().unwrap().scorer_advances, 2);
        assert!(trace.lock().unwrap().scorer_seeks.is_empty());

        // Advance to doc 4: similarly passes doc 3 via advance()
        assert_eq!(fps.advance(), 4);
        assert_eq!(trace.lock().unwrap().scorer_advances, 4);
        assert!(trace.lock().unwrap().scorer_seeks.is_empty());

        assert_eq!(fps.advance(), TERMINATED);
    }

    #[test]
    fn test_scorer_driven_range_gap_leaps_with_seek() {
        let trace = Arc::new(Mutex::new(Trace::default()));
        // Scorer has docs 0..100. Filter has docs 50..60.
        // On doc 0: miss, next doc in filter is 50. bound = 50 > 0 + 1.
        // Should leap via scorer.seek(50)!
        let scorer_docs: Vec<DocId> = (0..100).collect();
        let filter_docs: Vec<DocId> = (50..60).collect();
        let scorer = MockScorer::new(scorer_docs, 1000, trace.clone());
        let filter = MockFilter::new(filter_docs, 500, trace.clone());
        let mut fps = FilteredPruningScorer::new(scorer, filter);
        assert!(!fps.is_filter_driven());

        assert_eq!(fps.doc(), 50);
        // Scorer leaped to 50 via seek
        assert!(trace.lock().unwrap().scorer_seeks.contains(&50));
        assert_eq!(fps.advance(), 51);
    }

    #[test]
    fn test_filter_driven_sparse_iteration() {
        let trace = Arc::new(Mutex::new(Trace::default()));
        // Filter matches only docs 10 and 90 out of 100 docs.
        let scorer_docs: Vec<DocId> = (0..100).collect();
        let filter_docs = vec![10, 90];
        let scorer = MockScorer::new(scorer_docs, 1600, trace.clone());
        let filter = MockFilter::new(filter_docs, 2, trace.clone());
        let mut fps = FilteredPruningScorer::new(scorer, filter);
        assert!(fps.is_filter_driven());

        assert_eq!(fps.doc(), 10);
        assert_eq!(fps.advance(), 90);
        assert_eq!(fps.advance(), TERMINATED);
        // Filter-driven mode uses filter.advance() and scorer.seek()
        assert!(trace.lock().unwrap().filter_advances >= 1);
        assert!(trace.lock().unwrap().scorer_seeks.contains(&90));
    }
}
